# pylint: disable=C0114,C0103,C0115
# Generated by Django 4.1.2 on 2023-07-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=100)),
                ('webSite', models.CharField(max_length=100)),
            ],
        ),
    ]
